import Head from 'next/head'
import Main from '../components/Main/main';
import styles from '../styles/Home.module.css'

const Index = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
    </div>
  )
}

export default Index;